import { ArrowDownRight, ArrowRight, ArrowUpRight, Github, Linkedin, Mail, Menu, X, Code2, Layers3, Sparkles } from 'lucide-react';
import { motion, useReducedMotion } from 'motion/react';
import { useState } from 'react';
import { profile, metrics, projects, skillGroups, experience, education, caseStudies } from './data/portfolio';

const navigation = [{label:'About',href:'#about'},{label:'Projects',href:'#projects'},{label:'Case Studies',href:'#case-studies'},{label:'Expertise',href:'#expertise'},{label:'Experience',href:'#experience'},{label:'Contact',href:'#contact'}];

// Reusable entrance effect; reduced-motion users receive a static layout.
function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div className={className} initial={reduced ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ duration: .55, ease: 'easeOut' }}>{children}</motion.div>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="site-shell">
    <header className="site-header"><div className="container header-inner"><a href="#top" className="brand" aria-label="Back to top"><span className="brand-symbol">A<span>.</span></span><span className="brand-divider"/><span className="brand-caption">ANTONIO<br/>ÁLVAREZ</span></a><nav className={menuOpen ? 'nav nav-open' : 'nav'} aria-label="Main navigation">{navigation.map(n => <a key={n.href} href={n.href} onClick={() => setMenuOpen(false)}>{n.label}</a>)}</nav><a className="header-contact" href="#contact">Let's talk <ArrowUpRight size={16}/></a><button className="menu-toggle" type="button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></div></header>
    <main id="top"><section className="hero container"><div className="hero-glow" aria-hidden="true"/><Reveal><div className="eyebrow"><span className="status-dot"/> {profile.role.toUpperCase()} · BASED IN {profile.location.toUpperCase()}</div><h1>Hi, I'm <span className="gradient-text">{profile.name}.</span><br/><span className="hero-second-line">I build scalable digital products.</span></h1><p className="hero-description">{profile.introduction}</p><div className="hero-actions"><a className="btn btn-primary" href="#projects">Explore my work <ArrowUpRight size={18}/></a><a className="btn btn-outline" href="#contact">Get in touch <ArrowRight size={18}/></a></div><div className="hero-social"><a href={profile.github} target="_blank" rel="noreferrer"><Github size={17}/> GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17}/> LinkedIn</a><span className="social-line"/><span>SCROLL TO EXPLORE <ArrowDownRight size={15}/></span></div></Reveal><div className="hero-decoration" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-core"><Code2 size={48}/></div><span className="float-symbol symbol-one">&lt;/&gt;</span><span className="float-symbol symbol-two">{ '{ }' }</span></div></section>
    <section className="metrics-bar"><div className="container metrics-grid">{metrics.map(m => <div className="metric" key={m.label}><strong>{m.value}</strong><span>{m.label}</span></div>)}</div></section>
    <section className="section container" id="about"><Reveal><div className="section-heading"><span className="section-kicker">01 / ABOUT ME</span><h2>More than code.<br/><span className="muted-heading">Engineering with purpose.</span></h2></div><div className="about-grid"><p className="about-copy">{profile.about}</p><div className="about-aside"><div className="aside-icon"><Layers3 size={24}/></div><h3>From concept to production.</h3><p>Architecture, implementation, delivery, and continuous improvement — with an eye for the entire product lifecycle.</p></div></div></Reveal></section>
    <section className="section projects-section" id="projects"><div className="container"><Reveal><div className="section-heading split-heading"><div><span className="section-kicker">02 / SELECTED WORK</span><h2>Projects I've<br/><span className="muted-heading">been building.</span></h2></div><p>Selected personal and product projects. Public demos and repositories will be linked as they become available.</p></div></Reveal><div className="project-grid">{projects.map((p,i) => <Reveal key={p.name}><article className={'project-card project-tone-'+i}><div className="project-top"><span>{p.index} / FEATURED PROJECT</span><span className="project-status"><span className="tiny-dot"/>{p.status}</span></div><div className="project-art" aria-hidden="true"><div className="art-ring ring-outer"/><div className="art-ring ring-inner"/>{i===0?<Layers3 size={54}/>:i===1?<Code2 size={54}/>:<Sparkles size={54}/>}</div><div className="project-body"><span className="project-type">{p.type}</span><h3>{p.name}</h3><p>{p.description}</p><div className="tag-list">{p.stack.map(s=><span key={s}>{s}</span>)}</div>{p.url ? <a href={p.url} target="_blank" rel="noreferrer" className="project-link">View project <ArrowUpRight size={16}/></a> : <span className="project-unlinked">Case study coming soon <ArrowUpRight size={16}/></span>}</div></article></Reveal>)}</div></div></section>
    <section className="section container" id="case-studies"><Reveal><div className="section-heading split-heading"><div><span className="section-kicker">03 / PROFESSIONAL CASE STUDIES</span><h2>Real products.<br/><span className="muted-heading">Real engineering challenges.</span></h2></div><p>Selected contributions from professional roles. These are distinct from personal projects; confidential source code and client assets are not shown.</p></div></Reveal><div className="case-grid">{caseStudies.map((study) => <Reveal key={study.id}><article className="case-card" id={'case-'+study.id}><div className="case-heading"><span className="section-kicker">{study.number} / {study.category}</span><h3>{study.title}</h3><p>{study.overview}</p></div><div className="case-columns"><div><h4>The challenge</h4><p>{study.challenge}</p><h4>My contribution</h4><ul>{study.contribution.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="case-aside"><h4>Delivered work</h4><p>{study.outcome}</p><h4>Technologies & domains</h4><div className="tag-list">{study.stack.map((tech) => <span key={tech}>{tech}</span>)}</div><p className="case-note">{study.note}</p></div></div></article></Reveal>)}</div></section>
    <section className="section container" id="expertise"><Reveal><div className="section-heading"><span className="section-kicker">04 / TECHNICAL EXPERTISE</span><h2>Tools are important.<br/><span className="muted-heading">Solutions matter more.</span></h2></div><div className="skills-grid">{skillGroups.map((g,i)=><div className="skill-card" key={g.title}><span className="skill-number">0{i+1}</span><h3>{g.title}</h3><div className="tag-list">{g.skills.map(s=><span key={s}>{s}</span>)}</div></div>)}</div></Reveal></section>
    <section className="section container" id="experience"><Reveal><div className="section-heading"><span className="section-kicker">05 / PROFESSIONAL EXPERIENCE</span><h2>Experience built through<br/><span className="muted-heading">real-world engineering.</span></h2></div></Reveal><div className="experience-list">{experience.map((job) => <Reveal key={job.company}><article className="experience-card"><div className="experience-meta"><span className="experience-period">{job.period}</span><h3>{job.company}</h3><span className="experience-role">{job.role}</span></div><div className="experience-detail"><p>{job.description}</p><div className="tag-list">{job.highlights.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article></Reveal>)}</div><Reveal><div className="education-card"><div><span className="section-kicker">EDUCATION</span><h3>{education.institution}</h3><p>{education.degree} · {education.period} · {education.location}</p></div></div></Reveal></section>
    <section className="contact-section" id="contact"><div className="container"><Reveal><span className="section-kicker">06 / CONTACT</span><h2>Have something<br/><span className="gradient-text">great in mind?</span></h2><p>I'm always interested in meaningful engineering challenges, product ideas, and opportunities to collaborate.</p><div className="contact-actions">{profile.email && <a className="btn btn-primary" href={'mailto:'+profile.email}>Send an email <Mail size={18}/></a>}<a className="btn btn-outline" href={profile.linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight size={18}/></a></div></Reveal></div></section></main>
    <footer className="footer"><div className="container footer-inner"><span>© {new Date().getFullYear()} {profile.name}. Built with intention.</span><div><a href={profile.github} target="_blank" rel="noreferrer">GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn</a><a href="#top">Back to top ↑</a></div></div></footer>
  </div>;
}
